config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations",
                                    passwords:  "users/passwords" }
  resources :question_categories, only: :destroy
  resources :questions, only: [:index, :show, :destroy]
  resources :answers,   only: [:create, :update, :destroy]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :question_id, :user_id, :text, presence: true
  validates_uniqueness_of :user_id, scope: :question_id,
    message: "user can't have more than one answer to one question"
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def create
    @question = Question.find(answer_params[:question_id])
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to questions_path
    else
      @question = Question.find(answer_params[:question_id])
      render 'questions/show'
    end
  end

  def update
    if @answer.update_attributes(answer_params)
      redirect_to questions_path, status: 303
    else
      @question = Question.find(@answer.question_id)
      render 'questions/show'
    end
  end

  def destroy
    question_id = @answer.question_id
    @answer.destroy
# TODO: add AJAX
    redirect_to question_path question_id
  end

  private

  def answer_params
    params.require(:answer).permit(:text, :question_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/form.html.erb
<span class="answer-form">
  <% if @answer %>
    <%= form_for @answer, url: answer_path(@answer), method: :patch, remote: true do |f| %>
      <%= render 'questions/shared_show/text_area', f: f, question_id: @question_id %>
    <% end %>
  <% else %>
    <%= form_for :answer, url: answers_path, remote: true do |f| %>
      <%= render 'questions/shared_show/text_area', f: f, question_id: @question_id %>
    <% end %>
  <% end %>
</span>