config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations",
                                    passwords:  "users/passwords" }
  resources :question_categories, only: :destroy
  resources :questions, only: [:index, :show, :destroy]
  resources :answers,   only: [:create, :update, :destroy]
end

app/views/layouts/_top_navigation.html.erb
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Questionnaire', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_page?('/') %>
              <li class="active">
                <%= link_to '', root_path, class: 'glyphicon glyphicon-home' %>
              </li>
            <% else %>
              <li>
                <%= link_to '', root_path, class: 'glyphicon glyphicon-home' %>
              </li>
            <% end %>
            <% if current_user && current_user.activated == true %>
              <% if current_page?(controller: '/questions') %>
                <li class="active">
                  <%= link_to '', questions_path(type_questions:
                                                   'All questions'),
                                  class: 'glyphicon glyphicon-list' %>
                </li>
                <li>
                  <%= link_to '', edit_user_registration_path,
                                  class: 'glyphicon glyphicon-cog' %>
                </li>
              <% else %>
                <li>
                  <%= link_to '', questions_path(type_questions:
                                                   'All questions'),
                                  class: 'glyphicon glyphicon-list' %></li>
                </li>
                <% if current_page?(controller: 'users/registrations',
                                    action: 'edit') %>
                  <li class="active">
                    <%= link_to '', edit_user_registration_path,
                                class: 'glyphicon glyphicon-cog' %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to '', edit_user_registration_path,
                                class: 'glyphicon glyphicon-cog' %>
                  </li>
                <% end %>
              <% end %>
              <% if can? :access, :rails_admin %>
                <li class="dropdown">
                  <%= link_to "\u{2304}", '/admin',
                              class: 'dropdown-toggle glyphicon glyphicon-wrench',
                              'data-toggle' => 'dropdown',
                              role: 'button', 'aria-haspopup' => true,
                              'aria-expanded' => false %>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Dashboard', '/admin' %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to 'Answers', '/admin/answer' %></li>
                    <li><%= link_to 'Questions', '/admin/question' %></li>
                    <li><%= link_to 'Questions categories',
                                    '/admin/question_category' %></li>
                    <li><%= link_to 'Users', '/admin/user' %></li>
                    <li><%= link_to 'Users statuses',
                                    '/admin/user_status' %></li>
                  </ul>
                </li>
              <% end %>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <span class="pull-right log-out">
              <span>
                Hello, <%= current_user.name %>!
              </span><span class="tab"></span>
              <span class="status">
                (<%= UserStatus.find(current_user.user_status_id).name %>)
              </span><span class="tab"></span>
              <span class="answeres-amount">
                <%= Answer.where(user_id: current_user.id).count %>
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
              </span><span class="tab"></span>
              <%= link_to 'LOG OUT', destroy_user_session_path,
                          method: :delete, class: 'btn btn-primary' %>
            </span>
          <% else %>
            <%= form_for :user, url: user_session_path,
                         class: 'form-inline top-padding' do |f| %>
              <div class="log-in pull-right">
                <%= f.email_field :email, placeholder: 'E-mail',
                                          class: 'input-small' %>
                <%= f.password_field :password, autocomplete: "off",
                                                placeholder: 'Password',
                                                class: 'input-small' %>
                <%= f.submit 'LOG IN', class: 'btn btn-success' %>
                <%= link_to 'SIGN UP', new_user_registration_path,
                            id: 'sign_up_button', class: 'btn btn-primary' %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <%= favicon_link_tag %>
  <title>Questionnaire</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render 'layouts/top_navigation' %>
  <% if current_page?('/') %>
    <%= render 'welcome/carousel' %>
  <% end %><br /><br /><br /><br />
  <p class="notice text-primary notice-alert"><%= notice %></p>
  <p class="alert text-error notice-alert"><%= alert %></p>

  <%= yield %>

</body>
</html>